export const GO_TO_PAGE = 'GO_TO_PAGE'
export const SUBMIT_RESPONSE = 'SUBMIT_RESPONSE'

export const PREV_QUESTION = 'PREV_QUESTION'
export const NEXT_QUESTION = 'NEXT_QUESTION'

export const FETCH_DATA = 'FETCH_DATA'
export const RESET_SURVEY = 'RESET_SURVEY'
